server:
  port: 8080

spring:
  application:
    name: api-gateway

  main:
    web-application-type: reactive

  cloud:
    gateway:

      # 🔥 Gateway HTTP client timeout
      httpclient:
        connect-timeout: 2000
        response-timeout: 3s

      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: employee-service
          uri: lb://EMPLOYEE-SERVICE
          predicates:
            - Path=/employees/**
          filters:
            - name: CircuitBreaker
              args:
                name: employeeGatewayCircuit
                fallbackUri: forward:/fallback/employee

        - id: department-service
          uri: lb://DEPARTMENT-SERVICE
          predicates:
            - Path=/departments/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,beans,gateway,prometheus

  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true

  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG
    io.github.resilience4j.circuitbreaker: DEBUG
    
resilience4j:
  circuitbreaker:
    instances:
      employeeGatewayCircuit:
        sliding-window-size: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 2
        minimum-number-of-calls: 5
