server:
  port: 8081

spring:
  
  datasource:
    url: jdbc:mysql://localhost:3306/house_rent_mng_sys?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: prafful
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    io.github.resilience4j: DEBUG

    # ✅ Kafka Logging
    org.springframework.kafka: DEBUG
    org.apache.kafka: INFO
    org.apache.kafka.clients.producer: DEBUG
    org.apache.kafka.clients.NetworkClient: INFO


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
    

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,beans,gateway,prometheus
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
resilience4j:

  circuitbreaker:
    instances:
      departmentService:
        sliding-window-size: 5
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 2
        slow-call-rate-threshold: 50
        slow-call-duration-threshold: 2s

  retry:
    instances:
      departmentService:
        max-attempts: 3
        wait-duration: 1s
        retry-exceptions:
          - feign.RetryableException
          - java.io.IOException

  timelimiter:
    instances:
      departmentService:
        timeout-duration: 2s

  thread-pool-bulkhead:
    instances:
      departmentService:
        coreThreadPoolSize: 5
        maxThreadPoolSize: 10
        queueCapacity: 20
